name: Docker Image CI
 
on:

  push:
    branches: [ develop, master, release ]
    paths-ignore:
    - ".github/workflows/**"  
  
  workflow_dispatch:

jobs:
 
  build:

    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3 
      -  name: Login to registry
         uses: docker/login-action@v2
         with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PWD }}
    
      - name: Build the Docker image    
        run: |
             docker login ${{ secrets.REGISTRY_HOST }}
             docker build . --file Dockerfile --tag ${{ secrets.REGISTRY_HOST }}/${GITHUB_REF##*/}/serap-acompanhamento-front
             docker push ${{ secrets.REGISTRY_HOST }}/${GITHUB_REF##*/}/serap-acompanhamento-front
             
  deploy-dev:
  
    runs-on: self-hosted
    needs: [ build ]
    if: ${{ github.ref == 'refs/heads/develop' }}        
    environment:
      name: development
    steps:
      - name: Redeploy
        uses: prefeiturasp/SME-GithubAction-Images/@kubectl-v2.0
        env: 
          RANCHER_URL: ${{ secrets.RANCHER_URL }}
          RANCHER_TOKEN: ${{ secrets.RANCHER_TOKEN }}
          WORKLOAD: serap-acompanhamento-front
          NAMESPACE: sme-serap-acompanhamento
          
  deploy-hom:
  
    runs-on: self-hosted
    needs: [ build ]
    if: ${{ github.ref == 'refs/heads/release' }}        
    environment:
      name: release
    steps:
      - name: Redeploy
        uses: prefeiturasp/SME-GithubAction-Images/@kubectl-v2.0
        env: 
          RANCHER_URL: ${{ secrets.RANCHER_URL }}
          RANCHER_TOKEN: ${{ secrets.RANCHER_TOKEN }}
          WORKLOAD: serap-acompanhamento-front
          NAMESPACE: sme-serap-acompanhamento
          
  deploy-prod:
  
    runs-on: self-hosted
    needs: [ build ]
    if: ${{ github.ref == 'refs/heads/master' }}        
    environment:
      name: production
    steps:
      - name: Redeploy
        uses: prefeiturasp/SME-GithubAction-Images/@kubectl-v2.0
        env: 
          RANCHER_URL: ${{ secrets.RANCHER_URL }}
          RANCHER_TOKEN: ${{ secrets.RANCHER_TOKEN }}
          WORKLOAD: serap-acompanhamento-front
          NAMESPACE: sme-serap-acompanhamento
